apiVersion: v1
kind: Service
metadata:
  name: test-frr
  annotations:
        metallb.universe.tf/address-pool: address-pool-bgp
spec:
  selector:
        app: hello-node
  ports:
        - port: 9001
          protocol: TCP
          targetPort: 9376
  type: LoadBalancer
  loadBalancerIP: 192.168.155.151
